catalog/urls.py
from django.urls import path
from catalog import views

app_name="catalog"
urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.logout, name='logout'),
    path('waitingConfirmation/', views.waitingConfirmation, name='waitingConfirmation'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('myProfile/', views.myProfile, name='myProfile'),
    path('profile/<user_pk>', views.profile,  name='profile'),


]

chatRoom/urls.py
from django.urls import path, include

from . import views

app_name = 'chatRoom'
urlpatterns = [
    path('rooms/reportRoom/<room_pk>',views.reportRoom, name = 'reportRoom'),

    path('render_message', views.render_message,  name='render_message'),
    path('render_user_message', views.render_user_message,  name='render_user_message'),
    path('send_message', views.send_message,  name='send_message'),
    path('get_messages/<str:room_pk>/<str:last_time>', views.get_messages,  name='get_messages'),

    path('rooms/list',views.chat_rooms, name='roomsList'),
    path('rooms/leave/<room_pk>/<user_pk>/',views.leave, name='leave'),
    path('rooms/create', views.create_chat_room, name='roomsCreate'),
    path('rooms/<str:room_pk>', views.room,  name='room'),
    
    path('rooms/kickUser/<room_pk>/<user_pk>/<user_kick>', views.kickUser,  name='kickUser'),

    path('search/', include('haystack.urls')),
    path('manageReports/', views.manageReports, name='manageReports'),
    path('manageReports/manageReportsDelete/<room_pk>', views.manageReportsDelete, name='manageReportsDelete'),
]

webChat/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('chat/', include('chatRoom.urls')),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class User_validable(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(default=False)
    token = models.CharField(max_length=255, blank=True)    
    followed_tags = models.ManyToManyField(Tag,  related_name="User_tags", blank=True)
    
    def __str__(self):
        return self.user.username

catalog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth import authenticate
from datetime import date

class SignUp(forms.Form):
    user = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(min_length=8,max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    confirm_password = forms.CharField(min_length=8,max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    def clean_password(self):
        password = self.cleaned_data['password']
        if(len(password) < 8 or not password.isalnum() or password.isnumeric() or password.isalpha()):
            raise ValidationError(
                ["The password should be 8 characters at least.",
                "The password should be alphanumerical."])
        return password

    def clean_confirm_password(self):
        try:
            confirm_password = self.cleaned_data['confirm_password']
            password = self.cleaned_data['password']
            if password == confirm_password:
                return confirm_password
        except:
            pass    
        raise ValidationError(["Passwords didnt match"])

    def clean_user(self):
        user = self.cleaned_data['user']
        if User.objects.filter(username=user).exists():
            raise ValidationError("This user already exist.")
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email already exists")
        
        return email
    def clean_captcha(self):
        return self.cleaned_data['captcha']


class Login(forms.Form):
    user = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def clean_user(self):
        user = self.cleaned_data['user']
        if not User.objects.filter(username=user).exists():
            raise ValidationError("This user does not exist.")
        return user

    def clean_password(self):
        password = self.cleaned_data['password']
        try:
            username = self.cleaned_data['user']
        except:
            return password
        
        if(username is not None):
            user = authenticate(username=username, password=password)
            if user is None:
                raise ValidationError("Incorrect password.")
            print(user.password)
            return password
        return password

catalog/views.py
from django.contrib.auth.models import User, auth
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes

from django.core.mail import send_mail

from django.template.loader import render_to_string

from django.shortcuts import render,redirect

from django.http import HttpResponse

from datetime import timedelta
from django.utils import timezone

from catalog.forms import SignUp, Login 
from webChat import settings
from catalog.models import User_validable

def home(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        return render(request, 'home.html')
    return redirect('chatRoom:roomsList')

def login(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        pass
    auth.logout(request)
    form_login = Login()
    if request.method == 'POST':
        form_login = Login(request.POST)
        if form_login.is_valid():
            username = form_login.cleaned_data['user']
            password = form_login.cleaned_data['password']            
            user = authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                if User_validable.objects.get(user=(user)).is_confirmed:
                    return redirect('chatRoom:roomsList')
                else:
                    return redirect('catalog:waitingConfirmation')
            else:
                messages.warning(request,'Por favor ingrese un nombre de usuario y contraseña correctos')
    return render(request, 'login.html', {'form_login': form_login})

@login_required(login_url='/login/')
def logout(request):
    auth.logout(request)
    return redirect('/')

def waitingConfirmation(request):
    return render(request, 'waitingConfirmation.html')


def signup(request):
    auth.logout(request)
    form_signup = SignUp()
    if request.method == 'POST':
        form_signup = SignUp(request.POST)
        if form_signup.is_valid():
            user = form_signup.cleaned_data['user']
            email = form_signup.cleaned_data['email']
            password = form_signup.cleaned_data['password']

            user = User.objects.create_user(user, email, password)

            token = default_token_generator.make_token(user)
            user_validable = User_validable.objects.create(user=user, is_confirmed=False)
            user_validable.token = token
            user_validable.save()

            current_site = get_current_site(request)
            mail_subject = 'Activación Cuenta'
            message = render_to_string('active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [email]
            send_mail(mail_subject, message, email_from, recipient_list)

            return render(request, 'waitingConfirmation.html')

    return render(request, 'signup.html', {'form_signup': form_signup})

def activate(request, uidb64, token):
    UserModel = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None:
        user_validable = User_validable.objects.get(user=(user))
        if(token == user_validable.token):
            user_validable.is_confirmed = True
            user_validable.save()
            return HttpResponse('Gracias por su confirmación por correo electrónico. Ahora puede iniciar sesión en su cuenta')
    
    return HttpResponse('El enlace de activación no es válido.')


@login_required(login_url='/login/')
def construction(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        pass
    return render(request, 'construction.html')


@login_required(login_url='/login/')
def myProfile(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        pass
    return render(request, 'myProfile.html')

def profile(request, user_pk):
    try:
        user_viewed = User_validable.objects.get(pk=user_pk)
    except:
        pass
    return render(request, 'profile.html',{"user":user_viewed})

catalog/templates/active_email.html
{% autoescape off %}
Hola {{ user.username }},
Haga clic en el enlace para confirmar su registro,
http://{{ domain }}{% url 'catalog:activate' uidb64=uid token=token %}
Si cree que no es usted, ignore este correo electrónico.
{% endautoescape %}

catalog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'catalog/styles.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    <title>webChat!</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark primaryColor">
        <a class="navbar-brand" href="/">webChat!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'chatRoom:roomsList'%}">Chatrooms <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/chat/search/">Search <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'catalog:myProfile'%}">My profile <span class="sr-only">(current)</span></a>
            </li>
              {% if user.user.is_staff %}
                  <li class="nav-item active">
                  <a class="nav-link" href="{% url 'chatRoom:manageReports'%}">Manage Reports <span class="sr-only">(current)</span></a>
                  </li>
              {% endif %}
          </ul>
          {% if user.user.is_authenticated %}
            <a href="{% url 'catalog:logout' %}" class="text-decoration-none text-white-50" >Logout</a>
          {% else %}
            <a href="{% url 'catalog:login' %}" class="btn btn-success" >Login</a>
          {% endif %}
        </div>
      </nav>
      <div class="container">
        {% block section_name %}{% endblock %}

        {% block content %}{% endblock %}
      </div>
</body>
</html>

catalog/templates/chat.html
{%extends "base.html" %}
{% block content %}

<a href="/chat_rooms" class="btn btn-danger btn-lg btn-block w-25 m-2"> Leave </a>

<div class="container-center message-box">
    <div class="flex-row-around">
        <div class="chat-box">
            <textarea id="chat-log" class="w-100 h-50"></textarea><br>
            <div class="send-messagge-box">
                <input id="chat-message-input" type="text">
                <input id="chat-message-submit" type="button" value=">>">
            </div>
        </div>
        <div class="users-box">
            <h5>Users</h5>
            <ul>
                {% for user in chat.users.all%}
                <li>
                    <a href="/profile/{{user.pk}}">{{user}}</a>
                </li>
                {%endfor%}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/construction.html
{%extends "base.html" %}
{% block content %}

<div class="container-center">
    <p class="text-center">This page is under construction. Please come back later.</p>

    <div class="d-inline p-2 primaryHighligthColor text-white w-100 mb-1 text-center"><a class= "text-white" href="/">Volver a la home</a></div>
</div>

{% endblock %}

catalog/templates/home.html
{%extends "base.html" %}
{% block content %}

<div class="container-center">
    
    <h3 class="display-3">Welcome to <span class="font-weight-bold">webChat!</span></h3>

    <div class="d-inline p-2 primaryHighligthColor text-white w-100 mb-1 text-center"><a class= "text-white" href="{% url 'chatRoom:roomsList'%}">Start chatting!</a></div>
    <div class="d-inline p-2 primaryHighligthColor text-white w-100 mb-1 text-center"><a class= "text-white" href="{% url 'catalog:signup'%}">Sign up</a></div>
</div>

{% endblock %}

catalog/templates/login.html
{%extends "base.html" %}
{% block content %}
<div class="container-center ">
    <div class="card signup-login">
        <div class="card-body shadow-lg p-3 bg-white rounded">
            <h5 class="card-title">Iniciar sesión</h5>
            <form action="." method="POST">
                {% csrf_token %}
                {% for field in form_login %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {% if field.errors %}
                    <div class="errorBorder">
                        {{ field }}
                    </div>
                    <div class="errorMessagge">
                        {{field.errors}}
                    </div>
                    {%else%}
                    {{ field }}
                    {%endif%}
                </div>
                {% endfor %}
                <input type="submit" value="Iniciar sesión"
                    class="btn btn-primary btn-lg btn-block primaryHighligthColor primaryHighligthBorderColor">
            </form>
            <div class="p-2 w-100 mb-1 text-center"><a href="{% url 'catalog:signup' %}">New to webChat?</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/myProfile.html
{%extends "base.html" %}
{% block content %}
<div class="container-center">
    <div class="card signup-login">
        <div class="card-body shadow-lg p-3 bg-white rounded">
            <h3 class="card-title">{{user.user.username}}</h3>
            <div class="circle" >
                <img src="https://picsum.photos/2000" class="img-fluid" alt="Responsive image">
            </div>

            <br>
            <div class="form-group">
                <label type="email" class="text-black-50">Username</label>
                <br>
                <label type="password">{{user.user.username}}</label>
            </div>

            <div class="form-group">
                <label type="email" class="text-black-50">Email</label>
                <br>
                <label type="password">{{user.user.email}}</label>
            </div>

            <div class="form-group">
                <label type="email" class="text-black-50">Password</label>
                <br>
                <label type="password">**********</label>
            </div>

            
            <div class="form-group">
                <label type="email" class="text-black-50">Tags followed</label>
                <br>
                {% for tag in user.followed_tags.all %}                
                    <div class="badge badge-pill badge-primary p-0"> 
                        <a href="#" class="text-decoration-none text-white m-3"> {{tag.name}} </a>
                        <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                            <span aria-hidden="true">X</span>
                        </button>
                    </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/profile.html
{%extends "base.html" %}
{% block content %}
<div class="container-center">
    <div class="card signup-login">
        <div class="card-body shadow-lg p-3 bg-white rounded">
            <h3 class="card-title">{{user.username}}</h3>
            <div class="circle" >
                <img src="https://picsum.photos/2000" class="img-fluid" alt="Responsive image">
            </div>

            <br>
            <div class="form-group">
                <label type="email" class="text-black-50">Username</label>
                <br>
                <label type="password">{{user.username}}</label>
            </div>

            <div class="form-group">
                <label type="email" class="text-black-50">Email</label>
                <br>
                <label type="password">{{user.email}}</label>
            </div>

            <div class="form-group">
                <label type="email" class="text-black-50">Password</label>
                <br>
                <label type="password">**********</label>
            </div>

            
            <div class="form-group">
                <label type="email" class="text-black-50">Tags followed</label>
                <br>
                
                <div class="badge badge-pill badge-primary p-0"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="badge badge-pill badge-primary p-0"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="badge badge-pill badge-primary p-0"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="badge badge-pill badge-primary p-0 mb-1 mt-1"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="badge badge-pill badge-primary p-0"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="badge badge-pill badge-primary p-0"> 
                    <a href="#" class="text-decoration-none text-white m-3">Primary </a>
                    <button class="h-100 w-wrap rounded-right rounded-lg bg-light btn-sm btn border border-primary">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/signup.html
{%extends "base.html" %}
{% block content %}
<div class="container-center">
    <div class="card signup-login">
        <div class="card-body shadow-lg p-3 bg-white rounded">
            <h5 class="card-title">Registro de usuario</h5>
            <form action="." method="POST">
                {% csrf_token %}
                {% for field in form_signup %}
                    {% if field.label == 'Captcha' %}
                        {% if field.errors %}
                        <div class="form-group container-center mb-0">
                            {{ field }}
                        </div>
                        <div>
                            <div class="errorMessagge">
                                {{field.errors}}
                              </div>
                        </div>
                        {%else%}
                        <div class="form-group container-center">
                            {{ field }}
                        </div>
                        {%endif%}
                    {%else%}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {% if field.errors %}
                            <div class="errorBorder">
                                {{ field }}
                            </div>
                            <div class="errorMessagge">
                                {{field.errors}}
                            </div>
                            {%else%}
                            {{ field }}
                            {%endif%}
                        </div>
                    {%endif%}
                {% endfor %}
                <input class="btn btn-primary btn-lg btn-block primaryHighligthColor primaryHighligthBorderColor"
                    type="submit" value="Sign Up">
            </form>
            <div class="p-2 w-100 mb-1 text-center"><a href="{%url 'catalog:login' %}">Already have an account?</a></div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/waitingConfirmation.html
{%extends "base.html" %}
{% block content %}
Aún no has validado tu cuenta. No te olvides de hacerlo para poder disfrutar de todas las caracteristicas de la página.

<a href="{% url 'chatRoom:roomsList'%}">Ver chat rooms</a>


{% endblock %}