catalog/urls.py
from django.urls import path
from catalog import views

app_name="catalog"
urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.logout, name='logout'),
    path('waitingConfirmation/', views.waitingConfirmation, name='waitingConfirmation'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('myProfile/', views.myProfile, name='myProfile'),
    path('profile/<user_pk>', views.profile,  name='profile'),


]

chatRoom/urls.py
from django.urls import path, include

from . import views

app_name = 'chatRoom'
urlpatterns = [
    path('rooms/reportRoom/<room_pk>',views.reportRoom, name = 'reportRoom'),

    path('render_message', views.render_message,  name='render_message'),
    path('render_user_message', views.render_user_message,  name='render_user_message'),
    path('send_message', views.send_message,  name='send_message'),
    path('get_messages/<str:room_pk>/<str:last_time>', views.get_messages,  name='get_messages'),

    path('rooms/list',views.chat_rooms, name='roomsList'),
    path('rooms/leave/<room_pk>/<user_pk>/',views.leave, name='leave'),
    path('rooms/create', views.create_chat_room, name='roomsCreate'),
    path('rooms/<str:room_pk>', views.room,  name='room'),
    
    path('rooms/kickUser/<room_pk>/<user_pk>/<user_kick>', views.kickUser,  name='kickUser'),

    path('search/', include('haystack.urls')),
    path('manageReports/', views.manageReports, name='manageReports'),
    path('manageReports/manageReportsDelete/<room_pk>', views.manageReportsDelete, name='manageReportsDelete'),
]

webChat/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('chat/', include('chatRoom.urls')),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatRoom/models.py
from django.db import models
from catalog.models import User_validable, User, Tag
from django.utils import timezone
from django.utils.timezone import now

class Kicked_out_user(models.Model):
    user = models.ForeignKey(User_validable, on_delete=models.NOT_PROVIDED,)
    time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.user.user.username


class Type_Report(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Report(models.Model):
    usuario = models.ForeignKey(User_validable, on_delete=models.NOT_PROVIDED)
    motives = models.ManyToManyField('chatRoom.Type_Report', related_name="Reports_Motives")
    description = models.CharField(max_length=255)
    def __str__(self):
        return self.description

class Chatroom(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255)
    administrator = models.ForeignKey(User_validable, on_delete=models.CASCADE)
    moderators = models.ManyToManyField(User_validable,  related_name="Chat_moderators", blank=True)
    tags = models.ManyToManyField(Tag, related_name="Chatroom_tags")
    users = models.ManyToManyField(User_validable,  related_name="Chat_users", blank=True)
    banned_users = models.ManyToManyField(User_validable,  related_name="Chat_banned", blank=True)
    reports = models.ManyToManyField('chatRoom.Report',  related_name="Chat_reports", blank=True)
    kicked_out_user = models.ManyToManyField(Kicked_out_user,  related_name="Chat_kickeds", blank=True)
    messages_per_minute = models.IntegerField()
    time_between_messages = models.IntegerField()
    max_users = models.IntegerField()
    duration = models.IntegerField(blank=True,null=True)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User_validable, on_delete=models.CASCADE)
    message = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to="messages_images", blank=True)
    file = models.FileField(upload_to="messages_files", blank=True)
    time = models.DateTimeField(default=timezone.now)
    chatroom = models.ForeignKey(Chatroom, on_delete=models.CASCADE)
    type = models.CharField(max_length=255, default='chat_message')

    def __str__(self): 
        return str(self.pk) + '-' + self.chatroom.name + '-' + str(self.user.user.pk)

chatRoom/forms.py
from django import forms
from django.forms import ModelForm
from .models import Message, Chatroom, Report
from django.forms import ModelForm,TextInput, Textarea, ModelChoiceField, SelectMultiple, CheckboxSelectMultiple, FileInput


class New_Chatroom(ModelForm):
    class Meta:
        model = Chatroom
        fields = ["name","description","tags","messages_per_minute","time_between_messages", "max_users", "duration"]
        widgets = {
            'name': TextInput(attrs={'class':'form-control'}),
            'description': Textarea(attrs={'class':'form-control'}),
            'messages_per_minute': TextInput(attrs={'class':'form-control', 'type':'number', 'min':'0'}),
            'time_between_messages': TextInput(attrs={'class':'form-control', 'type':'number', 'min':'0'},),
            'max_users': TextInput(attrs={'class':'form-control', 'type':'number', 'min':'1'}),
            'duration': TextInput(attrs={'class':'form-control', 'type':'number', 'required':''}),
            'tags' : SelectMultiple(attrs={'class':'form-control'})
        }

    
    def clean_duration(self):
        duration = self.cleaned_data['duration']
        if(not duration):
            raise ValidationError("Duration is a required field")
        return duration          



class New_Report(ModelForm):
    class Meta:
        model = Report
        fields = ["motives", "description"]
        widgets = {
            'motives' : CheckboxSelectMultiple(),
            'description': Textarea(attrs={'class':'form-control'})
        }

    pass
class FormMessage(ModelForm):
    class Meta:
        model = Message
        fields = ["message","image","file", "user", "chatroom"]

chatRoom/views.py
from django.contrib.auth.models import User, auth
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.template import Context, Template
from django.template.loader import render_to_string

from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse

from datetime import timedelta
from django.utils import timezone
from catalog.models import User_validable
from .models import Chatroom, Kicked_out_user,Message,Tag, Report
from .forms import FormMessage, New_Chatroom, New_Report
from django.conf import settings

import json

from django.db.models import Q

def chat_rooms(request):
    userRooms = None
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
        userRooms = list(filter(lambda chatroom: not chatroom.duration or (chatroom.created_at.__add__(timedelta(hours=chatroom.duration)) > timezone.now()), Chatroom.objects.filter(users__user__pk__icontains=User_validable.objects.get(user=User.objects.get(username=request.user)).pk)))
    except:
        pass
    tags = Tag.objects.all()
    queryset = request.GET.get("search")
    querysetTags = request.GET.get("tags")
    
    if queryset is not None:
        rooms =  Chatroom.objects.filter(
            Q(name__icontains = queryset) |
            Q(description__icontains = queryset)
        )
    else:
        rooms = Chatroom.objects.all()
    if querysetTags is not None and querysetTags != '':
        rooms =  rooms.filter(
            tags__pk__icontains=querysetTags
        )

    filteredRooms = list(filter(lambda chatroom: not chatroom.duration or (chatroom.created_at.__add__(timedelta(hours=chatroom.duration)) > timezone.now()), rooms))
    contexto = {'rooms': filteredRooms, 'tags':tags, 'userRooms':userRooms, 'tagsSelected':querysetTags}
    if(userRooms is not None): 
        contexto = {'rooms': filteredRooms, 'tags':tags, 'userRooms':userRooms, 'tagsSelected':querysetTags}
    
    return render(request,'chat_rooms.html',contexto)
    
@login_required(login_url='/login/')
def create_chat_room(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        pass
    form_new_chatroom = New_Chatroom()
    if request.method == 'POST':
        form_new_chatroom = New_Chatroom(request.POST)
        if form_new_chatroom.is_valid() and validate_max_chatrooms(request.user):
            name = form_new_chatroom.cleaned_data['name']
            description = form_new_chatroom.cleaned_data['description']
            tags = form_new_chatroom.cleaned_data['tags']
            messages_per_minute = form_new_chatroom.cleaned_data['messages_per_minute']
            time_between_messages = form_new_chatroom.cleaned_data['time_between_messages']
            max_users = form_new_chatroom.cleaned_data['max_users']
            duration = form_new_chatroom.cleaned_data['duration']
            room = Chatroom.objects.create(
                name=name,
                description=description,
                messages_per_minute = messages_per_minute,
                time_between_messages = time_between_messages,
                max_users=max_users,
                duration=duration,
                administrator=User_validable.objects.get(user=(request.user.user)))

            room.save()
            room.tags.set(Tag.objects.filter(id__in=tags))
            room.users.set([request.user])
            room.save()
            return redirect('chatRoom:room',room_pk=room.pk)


    return render(request, 'create_chat_room.html', {'form_new_chatroom': form_new_chatroom})


def room(request, room_pk):
    chat = Chatroom.objects.get(pk=room_pk)
    form_report_chatroom = New_Report()
    form_send_message = FormMessage()
    if chat is not None:
        try:
            request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
            
            chat.users.add(request.user)
        except:
            pass
        return render(request,'room.html', {"chat": chat, 'form_send_message':form_send_message, 'room':room_pk, 'form_report_chatroom':form_report_chatroom})
    else:
        return render(None, '')
        

def reportRoom(request, room_pk):
#try:
    if request.method == 'POST':
        user = User_validable.objects.get(user=User.objects.get(username=request.user))
        chat = Chatroom.objects.get(pk=room_pk)
        form_report = New_Report(request.POST)

        if form_report.is_valid():
            report = Report.objects.create(
                description=form_report.cleaned_data['description'],
                usuario=user
            )
            report.motives.set(form_report.cleaned_data['motives'])
            report.save()
            chat.reports.add(report)
            chat.save()
            pass
#except:
#    pass


    return redirect('chatRoom:roomsList')

def manageReports(request):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
    except:
        pass
    rooms = Chatroom.objects.all()
    filteredRooms = list(filter(lambda chatroom: not chatroom.duration or (chatroom.created_at.__add__(timedelta(hours=chatroom.duration)) > timezone.now()), rooms))
    contexto = {'rooms': filteredRooms}

    return render(request, 'manageReports.html',contexto)

def manageReportsDelete(request, room_pk):
    try:
        request.user = User_validable.objects.get(user=User.objects.get(username=request.user))
        if request.method == 'POST':
            user = User_validable.objects.get(user=User.objects.get(username=request.user))
            sala = Chatroom.objects.get(pk=room_pk)
            sala.duration = -1
            sala.save()
    except:
        pass
    rooms = Chatroom.objects.all()
    filteredRooms = list(filter(lambda chatroom: not chatroom.duration or (chatroom.created_at.__add__(timedelta(hours=chatroom.duration)) > timezone.now()), rooms))
    contexto = {'rooms': filteredRooms}

    return redirect('chatRoom:manageReports')

def render_message(request):
    return render(request,'chatMessage.html', )
    

def render_user_message(request):
    return render(request,'chatUserMessage.html', )


def validate_max_chatrooms(user):
    x=0
    user_chatrooms = Chatroom.objects.filter(administrator=user)
    for chatroom in user_chatrooms:
        if(chatroom.duration is not None):
            if timezone.now() < chatroom.created_at.__add__(timedelta(hours=chatroom.duration)):
                x+=1
            if(x >= 3):
                return False
    return True

def send_message(request):
    if(request.method == 'POST'):
        strType = 'chat_message'
        strMessage = request.POST.get("message")
        strUserPk = request.POST.get("user")

        if(str(strMessage).startswith("/kick ")):
            splitted = str(strMessage).split(" ")
            if(len(splitted) == 2):
                strUserPk = User.objects.get(username=kickUser(request.POST.get("chatroom"), request.POST.get("user"), splitted[1]))
                if(strUserPk is None):
                    return JsonResponse({})
                strType = 'kick_message'
                strMessage = splitted[1] + " has been kicked out"
                
        form_message = FormMessage(request.POST, request.FILES)
        if form_message.is_valid():
            message = form_message.save()
            message.message = strMessage
            message.type = strType
            message.user = User_validable.objects.get(user=strUserPk)
            message.save()
            return JsonResponse(
                {
                    'type': strType,
                    'message': strMessage,
                    'userId': message.user.user.pk,
                    'userName': message.user.user.username,
                    'image': settings.MEDIA_URL+str(message.image),
                    'file': settings.MEDIA_URL+str(message.file)
                })
        else:
            return JsonResponse(form_message)



def get_messages(request, room_pk, last_time):
    if(request.method == 'GET'):
        if(last_time != "0"):
            messages = Message.objects.filter(chatroom=room_pk, time__gt=last_time).order_by('time')
        else:
            messages = Message.objects.filter(chatroom=room_pk).order_by('time')

        returnMessages = []
        for message in messages:
            returnMessages.append(
                {
                    'type': message.type,
                    'message': message.message,
                    'userId': message.user.user.pk,
                    'userName': message.user.user.username,
                    'image': settings.MEDIA_URL+str(message.image),
                    'file': settings.MEDIA_URL+str(message.file),
                    'last_time': str(message.time)
                }
            )
        return HttpResponse(json.dumps(returnMessages), content_type="application/json")


def leave(request, room_pk, user_pk):
    try:
        user_off = User_validable.objects.get(pk=user_pk)
        chat = Chatroom.objects.get(pk=room_pk)
        chat.users.remove(user_off)
    except:
        pass
    return redirect('chatRoom:roomsList')


def kickUser(room_pk, user_pk,user_kick):
    try:
        user_off = User_validable.objects.get(user=User.objects.get(username=user_kick))
        user_admin = User_validable.objects.get(pk=user_pk)
        chat = Chatroom.objects.get(pk=room_pk)
        if ((user_admin == chat.administrator)| (user_admin == chat.moderators)):
            chat.users.remove(user_off)
            chat.kicked_out_user.add(Kicked_out_user.objects.create(user = user_off, time=timezone.now()))
        else:
            return None
        return user_off
    except:
        return None
    

chatRoom/templates/chatMessage.html
<div class="bg-light p-2 chat-bubble m-2 d-inline-block" style="max-width: 45%;">
    <a href="#" class="text-decoration-none text-secondary">__user__</a>
    <a id="imageMessageLink" target="_blank"><img alt="" style="max-width: 200px; max-height: 200px; margin: 1px auto; display: block; margin-bottom: 10px;" id="imageMessage"></a>
    <p class="text-break bg-white p-2 chat-message m-0" id="chat-message">__messagge__</p>
    <a class="text-decoration-none text-secondary" id="fileLinkMessage" target="_blank" style="margin: 3px auto;display: block; text-align: center;">Download file!</a>
</div>

chatRoom/templates/chatUserMessage.html
<div class="primarySoftColor p-2 chat-bubble m-2 d-inline-block" style="max-width: 45%">
    <a id="imageMessageLink" target="_blank"><img alt="" style="max-width: 200px; max-height: 200px; margin: 1px auto; display: block; margin-bottom: 10px;" id="imageMessage"></a>
    <p class="text-break bg-white p-2 chat-message m-0" id="chat-message">__messagge__</p>
    <a class="text-decoration-none text-secondary" id="fileLinkMessage" target="_blank" style="margin: 3px auto;display: block; text-align: center;">Download file!</a>
</div>

chatRoom/templates/chat_rooms.html
{%extends "base.html" %}
{% block content %}

<form method="get">
    <div class="container m-5">
        <div class="row">
            <div class="col-md-12 search">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control" placeholder="Search.." name="search"
                            value="{{request.GET.search}}">
                        <span class="input-group-list">
                            <button type="submit" class="btn btn-success">Search</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container m-5">
        <div class="row">
            <div class="col-md-12 search">
                <div id="custom-search-input">
                    <div class="input-group" style="display:flex; flex-direction:row;justify-content: flex-start;">
                        <div id="tagsContainer">
                            {% for tag in tags %}
                                {% if tag.pk|stringformat:"s" == tagsSelected|stringformat:"s" %}
                                    <div class="badge badge-pill badge-secondary p-0 m-1">
                                        <button
                                            class="h-100 w-wrap rounded-right rounded-lg btn-sm btn border border-secondary text-decoration-none text-white m-1 bg-secondary"
                                            style="min-width: 60px;" name="tags" value=""><span>{{tag.name}}</span>
                                        </button>
                                    </div>
                                {% else %}
                                    <div class="badge badge-pill badge-primary p-0 m-1">
                                        <button
                                            class="h-100 w-wrap rounded-right rounded-lg btn-sm btn border border-primary text-decoration-none text-white m-1"
                                            style="min-width: 60px;" name="tags" value="{{tag.pk}}"><span>{{tag.name}}</span>
                                        </button>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
<div style="display:flex; flex-direction:row;justify-content: space-evenly;">
    <div class="container-center">
        <div class="flex-row-around">
            <h3 class="display-3">Chatrooms!</h3> <a href="create" class="m-3 btn btn-success h-50">Create your
                chatroom!</a>
        </div>
        <div class="flex-row-evenly">
            {% if rooms %}
            {% for room in rooms %}

            <div class="card m-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{room.name}}</h5>
                    <p class="card-text">{{room.description}}</p>
                    <a href="{% url 'chatRoom:room' room.pk %}"
                        class="btn btn-primary primaryHighligthColor primaryHighligthBorderColor w-100">Enter to
                        chat!</a>

                    <div class="flex-row-evenly">
                        {% for tag in room.tags.all %}
                        <div class="badge badge-pill badge-primary p-1 mt-2">
                            <a href="#" class="text-decoration-none text-white m-1">{{tag.name}} </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {% endfor %}

            {% else %}
            <h3 class="display-3">There are no ChatRooms</h3>
            {% endif %}

        </div>
    </div>
    <div class="card" style="width: 19rem;">
        <div class="card-body">
            <h3 class="card-title">My Chatrooms!</h3>
            {% for room in userRooms %}
            <a href="{% url 'chatRoom:room' room.pk %}"
                class="btn btn-light btn-sm w-100 primaryHighligthBorderColor">{{room.name}}</a>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

chatRoom/templates/create_chat_room.html
{%extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-center ">
    <div class="card signup-login">
        <div class="card-body shadow-lg p-3 bg-white rounded">
        <h5 class="card-title">Create chatroom</h5>
    
        <form method="POST" action="">
            {% csrf_token %}
            {% for field in form_new_chatroom %}
            <div class="form-group">
                {% if field.label != "Duration" %}
                    {% if field.label != "Time between messages" %}
                        <label>{{ field.label }}</label>
                    {%else%}
                        <label>Seconds between messages</label>
                    {% endif %}
                {%else%}
                    <label>Hours of duration</label>
                {% endif %}
                
                

                {% if field.errors %}
                <div class="errorBorder">
                    {{ field }}
                </div>
                <div class="errorMessagge">
                    {{field.errors}}
                </div>
                {%else%}
                {% if field.label != "Tags" %}
                {{ field }}
                {%else%}
                {{ field }}
                <div id="tagsContainer">

                </div>
                {%endif%}
                {%endif%}
            </div>
            {% endfor %}
            <input type="submit" value="Create chatroom" class="btn btn-primary btn-lg btn-block primaryHighligthColor primaryHighligthBorderColor">
               
            <script src="{% static 'catalog/index.js' %}"></script>
{% endblock %}

chatRoom/templates/room.html
{%extends "base.html" %}
{% load static %}
{% block content %}
{{ request.user.id|json_script:"user_id" }}
{{ request.user.user.username|json_script:"user_name" }}
{{ chat.pk|json_script:"room_id" }}
{{ chat.time_between_messages|json_script:"time_between_messages" }}
{{ chat.messages_per_minute|json_script:"messages_per_minute" }}

<link rel="stylesheet" href="{% static 'chatRoom/styles.css' %}">
<div class="chat-header">
    <h1 class="display-4">{{chat.name}}</h1>
    <a href="{%url 'chatRoom:leave' chat.pk request.user.id%}" class="btn btn-large btn-secondary"
        title="Leave chatroom" id="leave-chatroom">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-box-arrow-in-left" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z" />
            <path fill-rule="evenodd"
                d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
        </svg>
    </a>
    {% if chat.administrator.pk != user.pk %}
    {% if user.user.is_authenticated %}
    <a href="#victorModal" role="button" class="btn btn-large btn-danger" data-toggle="modal" title="Report chatroom"
        id="open-report-modal">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-clipboard-x" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z" />
            <path fill-rule="evenodd"
                d="M9.5 1h-3a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3zm-.354 7.146a.5.5 0 0 1 .708 0L8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 0 1 0-.708z" />
        </svg>
    </a>
    <div id="victorModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <form method="POST" action="reportRoom/{{chat.pk}}">
                        {% csrf_token %}
                        {{ form_report_chatroom }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Report</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>
<div class="container-center message-box">
    <div class="flex-row-around">
        <div class="chat-box">
            <div id="chat-log" class="w-100 h-50 pb-2 pt-2 overflow-auto" style="max-height: 50%"></div>
            <form action="POST"  id="formularioSendMessage">
                {% csrf_token %}
                <div class="send-messagge-box w-100 container-center-no-m">
                    {% if chat.administrator.pk == user.pk %}
                    <p class="font-italic m-1 mt-3"> say: [/kick "username"] to kick a user </p>
                    {% endif %}
                    {% if user.user.is_authenticated %}
                    <div class="w-100 flex-row-around mt-0 mb-0">
                        <input id="chat-message-input" type="text" class="form-control mr-1">
                        <input id="chat-message-submit" type="submit" value=">>" class="btn btn-success">
                    </div>
                    <div class="attachments mt-2 mb-2 w-100">
                        <div class="custom-file">
                            <input type="file" name="image" accept="image/*" id="image" class="custom-file-input" aria-describedby="imageAddon01">
                            <label class="custom-file-label" for="image">Select an image</label>
                        </div>
                        <div class="custom-file">
                            <input type="file" name="file" id="file" class="custom-file-input" aria-describedby="fileAddon01">
                            <label class="custom-file-label">Select a file</label>
                        </div>
                    </div>
                    {% endif %}
                </div>

            </form>
        </div>
        <div class="users-box">
            <h5>Users</h5>
            <ul id="usersList">
                {% for user in chat.users.all%}
                <li>
                    <a class="btn btn-light btn-sm" href="/profile/{{user.pk}}">Profile {{user}}</a>
                </li>
                {%endfor%}
            </ul>
        </div>
    </div>
    <script src="{% static 'chatRoom/chatReceiveMessagesHandler.js' %}"></script>
    {% if user.user.is_authenticated %}
    <script src="{% static 'chatRoom/chatSendMessagesHandler.js' %}"></script>
    {%endif%}
</div>
{% endblock %}